// Code generated by protoc-gen-nidhi. DO NOT EDIT.
// source: example/example.proto

package fuzz

import (
	fuzz "github.com/google/gofuzz"
	pb "github.com/srikrsna/protoc-gen-fuzz/example"
)

func FuzzSomeMessage(msg *pb.SomeMessage, c fuzz.Continue) {
    c.Fuzz(&msg.StringField)
    c.Fuzz(&msg.Int32Field)
    c.Fuzz(&msg.BoolField)
    c.Fuzz(&msg.InnerMessage)
    c.Fuzz(&msg.SliceString)
    c.Fuzz(&msg.SliceMessage)
    switch c.Int31n(2) {
    case 0:
        var f pb.SomeMessage_OneofString
        c.Fuzz(&f)
        msg.SomeOneof = &f
    case 1:
        var f pb.SomeMessage_OneofBool
        c.Fuzz(&f)
        msg.SomeOneof = &f
    }
}
 
func FuzzSomeMessage_OneofString(msg *pb.SomeMessage_OneofString, c fuzz.Continue) {
    c.Fuzz(&msg.OneofString)
}
 
func FuzzSomeMessage_OneofBool(msg *pb.SomeMessage_OneofBool, c fuzz.Continue) {
    c.Fuzz(&msg.OneofBool)
}

func FuzzInnerMessage(msg *pb.InnerMessage, c fuzz.Continue) {
    c.Fuzz(&msg.InnerField)
}
